version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.5-browsers
    steps:
      - checkout
      - run: 
          name: Install
          command: npm install
      - run:
          name: Run Tests
          command: npm test

