version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3
  
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: Angular
      - run: 
          name: Install
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Deploy
          command: npm run aws-deploy


          