version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: 
          name: Install
          command: npm install
      -run:
          name: Angular Cli
          command: npm install -g @angular/cli
      - run:
          name: Run Tests
          command: ng test