version: 2.1

  
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: 
          name: Install
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Deploy
          command: npm run aws-deploy
          
orbs:
  aws-cli: circleci/aws-cli@1.3

workflows:
  aws-cli:
    jobs:
      - build

#       - aws-s3/sync:
#           arguments: |
#             --acl public-read \
#             --cache-control "max-age=86400"
#           aws-access-key-id: $AWS_ACCESS_KEY_ID
#           aws-region: $AWS_REGION
#           aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
#           from: bucket
#           overwrite: true
#           to: 's3://angular-cloudfront-test/prefix'

#       - aws-s3/copy:
#           arguments: '--dryrun'
#           from: bucket/build_asset.txt
#           to: 's3://angular-cloudfront-test'


# workflow:
#   build-deploy:
#     jobs:
#       - build

# aws deploy create-application --application-name Angular-Jasmine
# aws deploy push --application-name Angular-JK --s3-location s3://angular-cloudfront-test/Angular-Jasmine.zip --ignore-hidden-files
               