version: 2.1
jobs:
  run-task:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: 
          name: Install
          command: npm install
      - run:
          name: Run Tests
          command: npm test


workflow:
  build-and-deploy:
    jobs:
      - run-task
      - aws-s3/sync:
            arguments: |
              --acl public-read \
              --cache-control "max-age=86400"
            aws-access-key-id: ${AWS_ACCESS_KEY_ID}
            aws-region: ${AWS_REGION}
            aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
            from: bucket
            overwrite: true
            to: 's3://angular-cloudfront-test/prefix'
      - aws-s3/copy:
            arguments: '--dryrun'
            from: bucket/build_asset.txt
            to: 's3://angular-cloudfront-test'

          